language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t susgupta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true susgupta/react-test yarn test -- --coverage

after_success:
  - docker build -t susgupta/multi-client ./client
  - docker build -t susgupta/multi-nginx ./nginx
  - docker build -t susgupta/multi-server ./server
  - docker build -t susgupta/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to hub
  - docker push susgupta/multi-client
  - docker push susgupta/multi-nginx
  - docker push susgupta/multi-server
  - docker push susgupta/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-379755352894"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
